notifications:
  email: false

language: cpp
sudo: required
dist: trusty

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-3.9
    packages:
      - gdb
      - gfortran
      - liblapack-dev
      - clang-3.9

branches:
  only:
    - master

before_install:
  - cat /proc/sys/kernel/core_pattern
  - export XROOT=~/xroot
  - tools/extras/travis_install_bindeps.sh $XROOT

script:
  - CXX=clang++-3.9
    CFLAGS="-march=native"
    LDFLAGS="-llapack"
    INCDIRS="$XROOT/usr/include"
    LIBDIRS="$XROOT/usr/lib"
      tools/extras/travis_script.sh

after_failure:
  - tools/extras/travis_show_failures.sh
