name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make tools
      run: cd tools && make -j3
    - name: configure
      run: cd src && ./configure --shared
    - name: make depend
      run: cd src && make depend
    - name: make 
      run: cd src && make 
    - name: make test
      run: cd src && make test
