name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    

jobs:

  docker-buildx:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Inspect builder
      run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
          
    - name: Build 
      run: |
          cd docker/ubuntu18.04-cuda10.0/
          docker build --tag jtrmal/kaldi:gpu-latest --tag jtrmal/kaldi:gpu-ubuntu18.04-cuda10.0 .
          
    - name: Push
      run: |
          cd docker/ubuntu18.04-cuda10.0/
          docker push jtrmal/kaldi:gpu-latest  .
          

          
      #uses: docker/build-push-action@v3
      #with:
      #  context: "{{ defaultContext }}:docker/ubuntu18.04-cuda10.0"
      #  file: /home/runner/work/kaldi/kaldi/docker/ubuntu18.04-cuda10.0/Dockerfile
      #  push: false
      #  tags: jtrmal/gpu:latest
        
        #context: "{{ defaultContext }}:docker/ubuntu18.04-cuda10.0"
        #file: "{{ defaultContext }}:docker/ubuntu18.04-cuda10.0/Dockerfile"
        
#tags: jtrmal/test:$(date +%s),jtrmal/gpu:latest          
#    - name: Build the Docker image
#      run: cd docker/ubuntu18.04-cuda10.0/; docker build . --file Dockerfile --tag kaldiasr/kaldi:gpu-ubuntu18.04-cuda10.0-$(date +%s)
      
