name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    
    - uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: "${{defaultContext}}:docker/ubuntu18.04-cuda10.0"
        file: "{{defaultContext}}:docker/ubuntu18.04-cuda10.0/Dockerfile"
        push: true
        tags: jtrmal/test:$(date +%s),jtrmal/gpu:latest
          
#    - name: Build the Docker image
#      run: cd docker/ubuntu18.04-cuda10.0/; docker build . --file Dockerfile --tag kaldiasr/kaldi:gpu-ubuntu18.04-cuda10.0-$(date +%s)
      
